inveniosoftware/invenio-oauthclient

invenio_oauthclient/handlers.py
invenio_oauthclient/templates/invenio_oauthclient/_macros.html
invenio_oauthclient/templates/invenio_oauthclient/rejected.html
invenio_oauthclient/templates/invenio_oauthclient/settings/index.html
invenio_oauthclient/templates/invenio_oauthclient/signup.html

* Uses gettext function to make template text translatable.
(addresses #12)

templates: translatable text addition

---

invenio_oauthclient/ext.py
tests/test_app.py

* Fixes the initialization of the extension when there is no
oauthlib.client object in extensions.
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

ext: fix init without oauthlib.client extension

---

docs/api.rst
invenio_oauthclient/contrib/cern.py
invenio_oauthclient/contrib/github.py
invenio_oauthclient/handlers.py
invenio_oauthclient/signals.py
setup.py

* Removes the dependency on Invenio-Groups reducing the number of fields
parsed inside CERN or ORCID modules and sending the response to a
subscribable signal. (closes #18)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

contrib: removal of dependency on Invenio-Groups

---

setup.py

* Pins HTTPretty version to 0.8.10 due to broken compatibility with
Python 3.  (addresses gabrielfalcao/HTTPretty#269)
--
or we should wait for https://github.com/gabrielfalcao/HTTPretty/pull/277

installation: HTTPretty==0.8.10 version pin

---

examples/cern_app.py

* Adds an example application using CERN authentication.
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

examples: addition of CERN authentication app

---

examples/github_app.py
examples/orcid_app.py
invenio_oauthclient/contrib/orcid.py
invenio_oauthclient/handlers.py
invenio_oauthclient/utils.py
setup.py
tests/test_views.py

* Introduces the possibility to "ask for email confirmation" in case
the provider doesn't return any user email (e.g. with orcid).

global: fix user register

---

invenio_oauthclient/ext.py
invenio_oauthclient/templates/invenio_oauthclient/_macros.html
invenio_oauthclient/templates/invenio_oauthclient/login_user.html

* Adds a macro to generate the links to connect with the installed
OAuth services.
* Adds a login_user.html template with the form showing the
OAuth services to login and the fields to a regular login.
(closes #26)
Co-Authored-By: Jiri Kuncar <jiri.kuncar@cern.ch>
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

templates: addition of OAuth login buttons macro

---

invenio_oauthclient/config.py
invenio_oauthclient/ext.py
invenio_oauthclient/utils.py
tests/test_app.py

* NEW Enables to create custom OAuthRemoteApp instances by replacing
the default remote application factory. (closes #45)
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>

global: new configurable OAuthRemoteApp factory

---

RELEASE-NOTES.rst
invenio_oauthclient/translations/de/LC_MESSAGES/messages.po
invenio_oauthclient/translations/es/LC_MESSAGES/messages.po
invenio_oauthclient/translations/fr/LC_MESSAGES/messages.po
invenio_oauthclient/translations/invenio.pot
invenio_oauthclient/translations/it/LC_MESSAGES/messages.po
setup.cfg
setup.py
tests/conftest.py
tests/test_contrib_cern.py
tests/test_contrib_github.py
tests/test_contrib_orcid.py
tests/test_models.py
tests/test_views.py

* Changes `invenio-software.org` to `inveniosoftware.org` to use the
same dashless canonical ID everywhere (GitHub, Twitter, Web).
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

global: inveniosoftware.org

---

examples/cern_app.py
examples/github_app.py
examples/orcid_app.py
invenio_oauthclient/config.py
invenio_oauthclient/contrib/cern.py
invenio_oauthclient/contrib/github.py
invenio_oauthclient/contrib/orcid.py
invenio_oauthclient/utils.py
invenio_oauthclient/version.py
invenio_oauthclient/views/client.py
invenio_oauthclient/views/settings.py

* Fixes an issue where `g.identity.provides` was populated with only the
Cern groups. As access rights can be assigned to single users(i.e. emails),
the user's e-mail must also be included in the `g.identity.provides`.

contrib: minor CERN plugin fix

---

invenio_oauthclient/admin.py
invenio_oauthclient/models.py
run-tests.sh
tests/__init__.py
tests/helpers.py

* Fixed the backref relationships in models.
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>

global: sqlalchemy relationships refactor

---

invenio_oauthclient/models.py
tests/conftest.py
tests/helpers.py
tests/test_contrib_github.py
tests/test_contrib_orcid.py
tests/test_handlers.py
tests/test_models.py
tests/test_utils.py
tests/test_views.py

* Increases test coverage. (closes #59)
Signed-off-by: Orestis Melkonian <melkon.or@gmail.com>

tests: coverage increase

---

invenio_oauthclient/handlers.py
invenio_oauthclient/signals.py

Needed in order to start celery task after all changes have been committed to the database. ``model_committed`` seems to me too unspecific to be useful in this connection.

signals: account setup committed signal

---

invenio_oauthclient/contrib/cern.py
tests/test_contrib_cern.py

* Renames configuration option for CERN hidden groups to properly
follow Invenio 3 naming style. (closes #76)
Signed-off-by: Orestis Melkonian <melkon.or@gmail.com>

contrib: CERN hidden groups config renaming

---

invenio_oauthclient/contrib/cern.py
setup.py
tests/test_contrib_cern.py

* Fixes a small typo in the `fetch_groups` method, which incorrectly retrieves
the `CERN_HIDDEN_GROUPS` instead of `CERN_HIDDEN_GROUPS_RE`.
Signed-off-by: Orestis Melkonian <melkon.or@gmail.com>

contrib: CERN typo fix

---

invenio_oauthclient/admin.py
setup.py

Fixes these warnings I just spotted on INSPIRE:
```
/Users/jacquerie/.virtualenvs/inspire/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.admin is deprecated, use flask_admin instead.
.format(x=modname), ExtDeprecationWarning
/Users/jacquerie/.virtualenvs/inspire/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.admin.contrib is deprecated, use flask_admin.contrib instead.
.format(x=modname), ExtDeprecationWarning
/Users/jacquerie/.virtualenvs/inspire/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.admin.contrib.sqla is deprecated, use flask_admin.contrib.sqla instead.
.format(x=modname), ExtDeprecationWarning
```
Not sure on `global:`, because it's a very …

global: ext warning fix

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_oauthclient/version.py
requirements-devel.txt
setup.cfg

This release is needed in order to release invenio-db without breaking invenio-app-ils (see 3a679aef2928bcf919663a6bb492b9a4f0480f30 and 5398bc17376a971527f4f65a47876d5e3965197b).
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>

Release v1.0.0a13

---

invenio_oauthclient/views/client.py

When you login with CERN OAuth and you go 'Back' it throughs an Internal Server Error
```
[2017-03-28 14:16:22 +0200] [13916] [ERROR] Error handling request /app/oauth/authorized/cern/?code=d73e90f281524c23970ee1a88987047a97999c979bcc41908e65d5fe229551e8&state=eyJhbGciOiJIUzI1NiIsImV4cCI6MTQ5MDcwMzY3MiwiaWF0IjoxNDkwNzAzMzcyfQ.eyJhcHAiOiJjZXJuIiwic2lkIjoiZDU4ODRmYjM0NDIxNWRiMjUwN2ViYzg3ZDNlZTFiZThiYjlhNzY0MDgyOTliY2M4ZThiYzIwOTM2ZGM5MTQzNTNiMDkzYjQ4Mjc3NjdiMzM4MzkyYzM1NDQxMTczNjY3MDNjYTc1ZmMyYzU4NjIzYzE2NmI0YjQ3ZGRkYTkwODAiLCJuZXh0IjoiLyJ9.jL4lLM5AFT2HQigFtIPuV1-1sOQ1RvqY4FSc_HvChYw
Traceback (most recent call last):
File "/Users/pamfilos/.envs/cap/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
self.handle_request(listener, req, client, addr)
File …
```

client: handles OAuthException

---

invenio_oauthclient/utils.py

* Allows oauth applications to set the remember parameter to
avoid session to expire. (closes #133)
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>

utils: pass remember parameter to login_user

---

invenio_oauthclient/contrib/cern.py
tests/conftest.py

* closes #112
Signed-off-by: Pamfilos Fokianos <pamfilosf@gmail.com>

cern: replaces 'PersonID' to 'uidNumber'

---

.travis.yml
invenio_oauthclient/views/settings.py

* do not show Linked Accounts -menuitem if no OAuth providers
have been configured.
Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>

admin: disable linked accounts menu item

---

docs/requirements.txt

* Fixes readthedocs.org documentation build. (addresses #146)

docs: fix readthedocs build

---

invenio_oauthclient/handlers.py
invenio_oauthclient/utils.py

* Auto fill csrf_token to avoid csrf validation error on self
submission. csrf_token validation flag differs from Flask-WTF
version 0.13 to 0.14. Moreover, the old flag will be removed on
Flask-WTF 1. (closes #115)
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>

handlers: fill csrf token on auto signup form

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_oauthclient/utils.py
invenio_oauthclient/version.py
setup.py
tests/helpers.py
tests/test_views.py

Returns always relative paths except if the `APP_ALLOWED_HOSTS`
variable is set, thus checks the host to be included in that list.

utils: Change redirect uri check

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_oauthclient/alembic/97bbc733896c_create_oauthclient_tables.py
invenio_oauthclient/models.py
invenio_oauthclient/version.py

sqlalchemy_utils recently [updated their `encrypted_type` module](https://github.com/kvesteri/sqlalchemy-utils/commit/7009afe4c8bb9bc14df5ffd205ba4aeaffbe2b75). `EncryptedType` now needs to be imported from `sqlalchemy_utils.types.encrypted.encrypted_type`.
Signed-off-by: Dinika Saxena <dinika.saxena@cern.ch>

import EncryptedType correctly from sqlalchemy_utils

---

LICENSE
docs/examplesapp.rst
docs/usage.rst
examples/globus_app.py
invenio_oauthclient/contrib/globus.py
tests/conftest.py
tests/test_contrib_globus.py
tests/test_examples_app.py

* Globus Login work for any provider Globus Auth supports
* Added tests, coverage of new code is 100%
* Added Sphinx docs

Added Globus as an identity provider

---

invenio_oauthclient/contrib/cern.py
invenio_oauthclient/errors.py
invenio_oauthclient/handlers.py
tests/test_contrib_cern.py

cern: allow users based on 'IdentityClass'

---

.travis.yml
CHANGES.rst
examples/app.py
examples/cern_app.py
examples/github_app.py
examples/globus_app.py
examples/orcid_app.py
invenio_oauthclient/_compat.py
invenio_oauthclient/ext.py
invenio_oauthclient/version.py
requirements-devel.txt
setup.py
tests/conftest.py

* updates python dependencies
* updates documentation links
* cleans travis.yml
closes #194

global: werkzeug compatibility patch

---

CHANGES.rst
invenio_oauthclient/utils.py
invenio_oauthclient/version.py
tests/test_utils.py

Fixes: https://github.com/inveniosoftware/invenio-oauthclient/issues/203

utils: decode redirect target

---

CHANGES.rst
invenio_oauthclient/handlers/__init__.py
invenio_oauthclient/version.py

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/188
- Ideal would be to rename ui exports (import as ....) but that would break compatibility with 1.3.0 release
- How could a test for this be made? Sadly it fails only at run time but without a IdP this cannot be checked...
Import works:
**RDM needs this released**

handlers: export rest handlers

---

invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/_macros.html
invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/base.html
invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/base_cover.html
invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/login_user.html
invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/rejected.html
invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/settings/base.html
invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/settings/index.html
invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/signup.html

templates: add semantic ui

---

invenio_oauthclient/contrib/orcid.py
invenio_oauthclient/views/client.py

* Adds error message when a remote server error occurs.
Signed-off-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>

contrib: fix orcid configuration

---

tests/conftest.py

This PR fixes the build in master. Closes #237 
The issue was that the session was being closed but the engine not disposed. And as explained [here](https://github.com/sqlalchemy/sqlalchemy/issues/5517) that mainly works as a "reset" so it was leaving connections open. In addition, the `drop_database` function was adding one more connection. Since the `base_app` fixture is `function` scoped, the amount of connections were piling up to a big amount (more than 200 in some cases, about 2 per test of the test suite).
Now they are left to 5 (along the whole test suite). Since I was connected to the mysql db too (to be able to query) the number of connections might be lower (e.g. 4) although there might be other services occupying connections (e.g. monitoring). In any case, connections are …

tests: dispose engine to avoid leaving open connections in mysql

---

invenio_oauthclient/contrib/cern_openid.py

* makes /userinfo endpoint configurable
* makes params passed to the JWT decode function configurable

contrib: fix retrieve user info in CERN OpenID

---

AUTHORS.rst
LICENSE
invenio_oauthclient/config.py
invenio_oauthclient/templates/invenio_oauthclient/login_user.html
invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/login_user.html
invenio_oauthclient/views/client.py
setup.py

partially closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/153
requires https://github.com/inveniosoftware/invenio-accounts/pull/368
TODO:
the provided config for `ACCOUNTS_LOGIN_VIEW_FUNCTION` should override the value from `invenio_accounts.config`, but doesn't

login: add possibility to auto-redirect to external auth services

---

invenio_oauthclient/contrib/cern.py
invenio_oauthclient/contrib/cern_openid.py
invenio_oauthclient/contrib/github.py
invenio_oauthclient/contrib/globus.py
invenio_oauthclient/contrib/keycloak/handlers.py
invenio_oauthclient/contrib/orcid.py
invenio_oauthclient/handlers/base.py
invenio_oauthclient/handlers/utils.py
invenio_oauthclient/templates/invenio_oauthclient/settings/index.html
invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/settings/index.html
invenio_oauthclient/views/settings.py
tests/conftest.py
tests/test_contrib_cern.py
tests/test_contrib_cern_openid.py
tests/test_contrib_cern_openid_rest.py
tests/test_contrib_cern_rest.py
tests/test_contrib_github.py
tests/test_contrib_github_rest.py
tests/test_contrib_globus.py
tests/test_contrib_keycloak.py
tests/test_contrib_orcid.py
tests/test_contrib_orcid_rest.py
tests/test_views.py

* this only applies if the user can't login to their local account
(either ACCOUNTS_LOCAL_LOGIN_ENABLED=False, or they don't have a
password set)
closes #251

settings: disable unlinking of last external account

---

invenio_oauthclient/contrib/cern.py
invenio_oauthclient/contrib/cern_openid.py
tests/test_contrib_cern.py
tests/test_contrib_cern_openid.py
tests/test_contrib_cern_openid_rest.py
tests/test_contrib_cern_rest.py

* skip CERN contrib signals when login happened via another login method
* closes #228

contrib: fix CERN contrib signal

---

invenio_oauthclient/handlers/utils.py
tests/conftest.py

- closes https://github.com/inveniosoftware/invenio-oauthclient/issues/267
@slint are tests needed? I can see for example in the ORCiD tests (`test_authorized_signup`), there is a test for the 400 error done when disconnecting (and then it works). I could test the decorator but not sure we can (because of mocking) test something in a meaningful way for the views.
https://user-images.githubusercontent.com/6756943/148374499-ffb3de72-d8e8-402b-9c1e-2854f75a8ccc.mov

handlers: fix linked account disconnection

---

invenio_oauthclient/ext.py
invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/_macros.html

Fixing an issue we noted on our side where clicking on the label of a checkbox in our registration form didn't toggle the checkbox.

templates: render 'for' attribute on checkbox label

---

invenio_oauthclient/alembic/bff1f190b9bd_add_timestamp_oauthclient.py
invenio_oauthclient/contrib/cern_openid.py
invenio_oauthclient/contrib/globus.py
invenio_oauthclient/utils.py
tests/test_contrib_cern_openid_rest.py
tests/test_contrib_github.py
tests/test_contrib_github_rest.py
tests/test_contrib_globus.py
tests/test_contrib_orcid.py
tests/test_contrib_orcid_rest.py

* fetch extra roles, cached in the DB, when the user login using a personal access token.
* closes #291

contrib: fix CERN contrib login with token

---

invenio_oauthclient/config.py
invenio_oauthclient/contrib/settings.py
invenio_oauthclient/ext.py
invenio_oauthclient/handlers/base.py
tests/conftest.py
tests/test_app.py
tests/test_handlers_rest.py
tests/test_handlers_ui.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2186
* NEEDS https://github.com/inveniosoftware/invenio-accounts/pull/439

base: add group handler 

---

invenio_oauthclient/contrib/settings.py
invenio_oauthclient/handlers/base.py
invenio_oauthclient/views/client.py

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/16

client: add logout blueprint

---

setup.cfg

This pull request fixes issue #299 - conflicting versions of the uritemplate library. Invenio sources in general use the `uritemplate` library, but this module uses the `uritemplate-py` library. Both of the libraries provide the same top-level `uritemplate` python module and the one used depends on the installation order.
In the pull request, the `uritemplate-py` library was replaced with `uritemplate`.
*Note:* it seems that invenio-theme 3.0.0 does not include `flask-breadcrumbs` anymore and this library depends on that. `flask-breadcrumbs` were added to test dependencies, not sure if it is correct.
**Third-party code**
If you've added [third-party code …

Fix conflicting versions of uritemplate library

---

invenio_oauthclient/contrib/keycloak/settings.py

closes #323 
Add flag for using the `auth/` part in the realm url.
Newer versions of keycloak do not have an `auth/` part in the realm url per default anymore. To not break existing InvenioRDM instances and oauth configurations, the flag is set to true per default.
This allows to keep all the other setup functionality and only modify the realm url if needed.
Keycloak v16 support has been deprecated for quite some time now ((11 Mar 2022) according to https://endoflife.date/keycloak).
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out …

fix: add flag for auth in keycloak realm url

---

invenio_oauthclient/contrib/settings.py
invenio_oauthclient/templates/invenio_oauthclient/login_user.html
invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/login_user.html
invenio_oauthclient/views/client.py
tests/conftest.py
tests/test_app.py
tests/test_views.py

A `hide` attribute is accessed at some places within the existing code already. These changes will explicitly set this attribute and use it in other places in the code as well. This will allow to hide login with an external account, while at the same time, allow to link an external account in the profile view.
Per default, `hide` will evaluate to `False` in order to be compliant with the current logic.
Example config:
```py
def anon_user():
return not current_user.is_authenticated
helper = k.KeycloakSettingsHelper(
title="Local KeyCloak",
description="My organization authentication provider",
base_url="http://localhost:8087",
realm="damap",
)
OAUTHCLIENT_REMOTE_APPS = dict(
orcid={
**orcid.REMOTE_APP,
"hide": LocalProxy(lambda: anon_user()),
}, …
```

global: explicitly set and use hide attribute for config

---

CHANGES.rst
invenio_oauthclient/__init__.py
invenio_oauthclient/alembic/97bbc733896c_create_oauthclient_tables.py
invenio_oauthclient/alembic/bff1f190b9bd_add_timestamp_oauthclient.py
invenio_oauthclient/models.py
setup.cfg

- setup: move to flask-oauthlib-invenio
- fix: TypeError
- fix: DeprecationWarning:
- release: v5.1.0

fix flask oauthlib invenio

---

invenio_oauthclient/admin.py
invenio_oauthclient/contrib/cern.py
invenio_oauthclient/contrib/cern_openid.py
invenio_oauthclient/contrib/github.py
invenio_oauthclient/contrib/globus.py
invenio_oauthclient/contrib/keycloak/helpers.py
invenio_oauthclient/contrib/openaire_aai.py
invenio_oauthclient/contrib/orcid.py
invenio_oauthclient/handlers/__init__.py
invenio_oauthclient/handlers/rest.py
invenio_oauthclient/handlers/token.py
invenio_oauthclient/handlers/ui.py
invenio_oauthclient/handlers/utils.py
invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/login_user.html
tests/test_contrib_keycloak.py

Fix: some strings that could appear inside UI were not marked with `gettext/lazy_gettext`. 
This PR adds `lazy_gettext` into places where the string is read when invenio is started (static initialization) and `gettext` elsewhere
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including …

Fix: i18n: added gettext to places where it was missing
