- AUTHORS.rst
- CHANGES.rst
- RELEASE-NOTES.rst
- docs/index.rst
- setup.cfg
- setup.py
> Invenio-OAuthClient v0.1.0

- AUTHORS.rst
- CHANGES.rst
- MANIFEST.in
- RELEASE-NOTES.rst
- invenio_oauthclient/version.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> Invenio-OAuthClient v0.1.1

- .gitignore
- .travis.yml
- babel.ini
- invenio_oauthclient/translations/de/LC_MESSAGES/messages.po
- invenio_oauthclient/translations/es/LC_MESSAGES/messages.po
- invenio_oauthclient/translations/fr/LC_MESSAGES/messages.po
- invenio_oauthclient/translations/invenio.pot
- invenio_oauthclient/translations/it/LC_MESSAGES/messages.po
- setup.cfg
- setup.py
- i18n: initial message extraction
> travis: fix environment creation

- invenio_oauthclient/forms.py
- invenio_oauthclient/handlers.py
- invenio_oauthclient/utils.py
- invenio_oauthclient/views/client.py
- invenio_oauthclient/views/settings.py
- requirements-devel.txt
- setup.py
- tests/helpers.py
- tests/test_views.py
* FIX Adds missing `invenio_base` dependency and amends past
upgrade recipes following its separation into standalone package.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
> installation: fix invenio_base imports

- invenio_oauthclient/contrib/cern.py
- invenio_oauthclient/contrib/orcid.py
- invenio_oauthclient/forms.py
- invenio_oauthclient/models.py
- invenio_oauthclient/upgrades/oauthclient_2014_03_02_initial.py
- invenio_oauthclient/utils.py
- invenio_oauthclient/views/client.py
- invenio_oauthclient/views/settings.py
- requirements-devel.txt
- setup.py
- tests/test_contrib_orcid.py
- tests/test_models.py
- tests/test_views.py
> global : fix invenio_utils imports

- docs/conf.py
- examples/app.py
- examples/github_app.py
- invenio_oauthclient/__init__.py
- invenio_oauthclient/config.py
- invenio_oauthclient/contrib/cern.py
- invenio_oauthclient/contrib/orcid.py
- invenio_oauthclient/ext.py
- invenio_oauthclient/handlers.py
- invenio_oauthclient/models.py
- invenio_oauthclient/proxies.py
- invenio_oauthclient/upgrades/oauthclient_2014_03_02_initial.py
- invenio_oauthclient/upgrades/oauthclient_2014_08_25_extra_data_nullable.py
- invenio_oauthclient/upgrades/oauthclient_2014_10_21_encrypted_token_column.py
- invenio_oauthclient/utils.py
- invenio_oauthclient/views/client.py
- invenio_oauthclient/views/settings.py
- tests/conftest.py
- tests/test_app.py
- tests/test_contrib_orcid.py
- tests/test_views.py
* BETTER Stores initialized handlers in extension state.
> global: stateful extension

- invenio_oauthclient/handlers.py
* Removes deprecated code. (addresses #12)
> handlers: deprecated code removal

- invenio_oauthclient/ext.py
> ext: removal of unused methods

- examples/github_app.py
- invenio_oauthclient/contrib/orcid.py
- invenio_oauthclient/handlers.py
- invenio_oauthclient/views/client.py
- setup.py
- tests/test_contrib_orcid.py
- tests/test_views.py
> installation: addition of Flask-Security>=1.7.5

- invenio_oauthclient/templates/invenio_oauthclient/settings/base.html
- invenio_oauthclient/templates/invenio_oauthclient/settings/index.html
* Fixes template block being used.
* Fixes site name configuration variable.
> settings: template fix

- examples/app.py
- examples/cern_app.py
- examples/github_app.py
- examples/orcid_app.py
- invenio_oauthclient/admin.py
- invenio_oauthclient/contrib/orcid.py
- invenio_oauthclient/models.py
- invenio_oauthclient/utils.py
- setup.py
- tests/conftest.py
- tests/test_admin.py
- tests/test_contrib_orcid.py
* Adds admin views for managing user OAuth tokens.
Reviewed-by: Jiri Kuncar <jiri.kuncar@cern.ch>
Signed-off-by: Bruno Cuc <bruno.cuc@cern.ch>
--
closes #33
> global: addition of admin views

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_oauthclient/translations/de/LC_MESSAGES/messages.po
- invenio_oauthclient/translations/es/LC_MESSAGES/messages.po
- invenio_oauthclient/translations/fr/LC_MESSAGES/messages.po
- invenio_oauthclient/translations/invenio.pot
- invenio_oauthclient/translations/it/LC_MESSAGES/messages.po
- invenio_oauthclient/version.py
> release: v1.0.0a1

- invenio_oauthclient/version.py
> version: post-release bump

- invenio_oauthclient/templates/invenio_oauthclient/settings/index.html
- invenio_oauthclient/views/settings.py
> views: menu highlighting fix

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_oauthclient/version.py
> release: v1.0.0a2

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_oauthclient/version.py
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
> release: v1.0.0a3

- CHANGES.rst
- RELEASE-NOTES.rst
- docs/conf.py
- invenio_oauthclient/contrib/github.py
- invenio_oauthclient/handlers.py
- invenio_oauthclient/utils.py
- invenio_oauthclient/version.py
- setup.py
- tests/conftest.py
- Fixes issue with `password=None` during registration.
- Adds better GitHub error handler.
> global: addition of missing commits

- invenio_oauthclient/contrib/github.py
- setup.py
This fixes problem for Invenio-GitHub that depends on github3.py==1.0.0a4.
> contrib: upgrade to github3.py==1.0.0a4

- .gitignore
- AUTHORS.rst
- examples/cern_app.py
- examples/github_app.py
- examples/orcid_app.py
- invenio_oauthclient/contrib/cern.py
- invenio_oauthclient/utils.py
- tests/conftest.py
- tests/helpers.py
- tests/test_contrib_cern.py
- tests/test_contrib_orcid.py
- tests/test_models.py
- tests/test_views.py
* CERN third-party authentication now completely working.
* Increases test coverage.
Signed-off-by: Orestis Melkonian <melkon.or@gmail.com>
Co-Authored-By: Esteban J. G. Gabancho <esteban.gabancho@gmail.com>
> contrib: CERN plugin fixes and testing

- .editorconfig
- AUTHORS.rst
- MANIFEST.in
- docs/api.rst
- docs/index.rst
- examples/orcid_app.py
- invenio_oauthclient/contrib/__init__.py
- invenio_oauthclient/contrib/github.py
- invenio_oauthclient/contrib/orcid.py
- invenio_oauthclient/errors.py
- invenio_oauthclient/models.py
- invenio_oauthclient/templates/invenio_oauthclient/rejected.html
- invenio_oauthclient/templates/invenio_oauthclient/settings/base.html
- invenio_oauthclient/templates/invenio_oauthclient/signup.html
- invenio_oauthclient/views/__init__.py
- invenio_oauthclient/views/client.py
- run-tests.sh
- setup.cfg
- tests/__init__.py
- tests/helpers.py
- tests/test_app.py
- tests/test_models.py
- tests/test_views.py
> global: correction of copyright years

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_oauthclient/version.py
> release: v1.0.0a7

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_oauthclient/version.py
- setup.py
> release: v1.0.0a8

- invenio_oauthclient/contrib/cern.py
- tests/test_contrib_cern.py
* Adds missing disconnect handler which unlinks CERN account.
(closes #82)
--
cc @ioannistsanaktsidis
> contrib: disconnect handler to unlink CERN account

- AUTHORS.rst
- CHANGES.rst
- RELEASE-NOTES.rst
- docs/index.rst
- invenio_oauthclient/contrib/__init__.py
- invenio_oauthclient/signals.py
- invenio_oauthclient/templates/invenio_oauthclient/rejected.html
- invenio_oauthclient/version.py
- invenio_oauthclient/views/__init__.py
- tests/test_handlers.py
- tests/test_utils.py
> release: v1.0.0a9

- README.rst
> docs: typo fix

- .tx/config
- README.rst
- invenio_oauthclient/contrib/cern.py
- invenio_oauthclient/contrib/github.py
- invenio_oauthclient/contrib/orcid.py
- invenio_oauthclient/models.py
- invenio_oauthclient/views/client.py
- run-tests.sh
> global: automatically sorted imports

- invenio_oauthclient/contrib/cern.py
- invenio_oauthclient/utils.py
- tests/test_handlers.py
- tests/test_utils.py
* Removes session after logout.
Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>
> contrib: adds CERN groups after user is logged in

- docs/conf.py
- invenio_oauthclient/contrib/cern.py
- invenio_oauthclient/contrib/github.py
- invenio_oauthclient/contrib/orcid.py
- invenio_oauthclient/handlers.py
- invenio_oauthclient/models.py
- invenio_oauthclient/utils.py
- setup.py
* Improves documentation. (addresses #73)
* Fixes an compatibility issue of cryptography old versions with
cffi new version. (closes #100)
> docs: addition of param and result sections & fix lowest requirements

- MANIFEST.in
- RELEASE-NOTES.rst
- docs/requirements.txt
- invenio_oauthclient/__init__.py
- invenio_oauthclient/config.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> docs: move to readthedocs.io

- examples/github_app.py
- examples/orcid_app.py
- invenio_oauthclient/_compat.py
- invenio_oauthclient/contrib/cern.py
- invenio_oauthclient/contrib/github.py
- invenio_oauthclient/contrib/orcid.py
- invenio_oauthclient/handlers.py
- invenio_oauthclient/views/client.py
- invenio_oauthclient/views/settings.py
- requirements-devel.txt
- setup.py
- tests/helpers.py
- tests/test_contrib_github.py
- tests/test_contrib_orcid.py
- tests/test_handlers.py
- tests/test_views.py
* Removes Flask-Security usage with other alternatives from already
existing dependencies.
> global: removal of Flask-Security usage

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_oauthclient/alembic/44ab9963e8cf_create_oauthclient_branch.py
- invenio_oauthclient/alembic/97bbc733896c_create_oauthclient_tables.py
- invenio_oauthclient/contrib/cern.py
- invenio_oauthclient/version.py
- invenio_oauthclient/views/settings.py
- setup.py
- tests/test_app.py
> release: v1.0.0a12

- invenio_oauthclient/alembic/44ab9963e8cf_create_oauthclient_branch.py
- invenio_oauthclient/alembic/97bbc733896c_create_oauthclient_tables.py
- invenio_oauthclient/contrib/cern.py
- invenio_oauthclient/views/settings.py
- setup.py
- tests/test_app.py
> global: initial alembic recipes

- invenio_oauthclient/contrib/orcid.py
- tests/conftest.py
- tests/test_contrib_orcid.py
- Stores the authors full name on orcid sign-up.
Signed-off-by: Panos Paparrigopoulos panos.paparrigopoulos@cern.ch
> contrib: save full name from orcid

- invenio_oauthclient/models.py
- setup.py
> installation: sphinx version fix

- .editorconfig
- .gitignore
- CONTRIBUTING.rst
- INSTALL.rst
- MANIFEST.in
- docs/Makefile
- docs/make.bat
- requirements-devel.txt
- setup.py
* FIX Adds changes according to release preparation checklist.
Signed-off-by: Paulina Lach <paulina.malgorzata.lach@cern.ch>
> global: release checklist

- invenio_oauthclient/utils.py
- setup.py
- tests/test_utils.py
Signed-off-by: Dinos Kousidis <konstantinos.kousidis@cern.ch>
> entry point function for SECRET_KEY change

- MANIFEST.in
- examples/app-setup.sh
- examples/app-teardown.sh
- examples/app.py
- examples/cern_app.py
- examples/github_app.py
- examples/orcid_app.py
- setup.py
- tests/test_examples_app.py
- Adds test_examples_app.py. (closes #94)
Signed-off-by: Leonardo Rossi leonardo.r@cern.ch
> tests: addition of test_examples_app.py

- setup.py
> installation: api_apps application registering

- invenio_oauthclient/templates/invenio_oauthclient/_macros.html
- invenio_oauthclient/templates/invenio_oauthclient/login_user.html
* Fixes issues with remote app redirection after successful login.
(closes #139)
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> templates: addition of next parameter

- setup.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> setup: addition of `Flask-Security` v3.0.0

- invenio_oauthclient/templates/invenio_oauthclient/_macros.html
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> templates: update render_field macro

- .travis.yml
- invenio_oauthclient/config.py
- invenio_oauthclient/handlers.py
- invenio_oauthclient/utils.py
- tests/test_examples_app.py
* Disables remember me feature. (closes #138)
> global: remember me disabled

- invenio_oauthclient/admin.py
- invenio_oauthclient/models.py
- setup.py
- tests/test_admin.py
* Amends remote account and token names in admin UI. (closes #151)
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>
> admin: add user identity admin view

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_oauthclient/version.py
- setup.py
> release v1.0.0b2

- docs/usage.rst
(Closes https://github.com/inveniosoftware/invenio-oauthclient/issues/162)
Signed-off-by: Dinos Kousidis <konstantinos.kousidis@cern.ch>
> docs: remove advanced section

- invenio_oauthclient/models.py
- tests/test_models.py
> models: hide part of the access_token in repr

- invenio_oauthclient/alembic/bff1f190b9bd_add_timestamp_oauthclient.py
- invenio_oauthclient/models.py
* alembic: create recipe to add 'created' and 'updated' columns
* close #160
> models: add 'sqlalchemy_utils.models.Timestamp' mixin

- docs/requirements.txt
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
> docs: add github requirement

- .travis.yml
Closes https://github.com/inveniosoftware/invenio-oauthclient/issues/170
Signed-off-by: Dinos Kousidis <konstantinos.kousidis@cern.ch>
> travis: add deploy condition

- tests/test_views.py
* Closes #174.
Signed-off-by: Sebastian Witowski <witowski.sebastian@gmail.com>
> flask 1.0 fix

- .travis.yml
- examples/cern_app.py
- examples/github_app.py
- examples/globus_app.py
- examples/orcid_app.py
- invenio_oauthclient/contrib/github.py
Signed-off-by: Leticia Farias Wanderley <leticia.farias.wanderley@cern.ch>
> examples: fix setup file extension

- invenio_oauthclient/ext.py
- invenio_oauthclient/handlers.py
> ext: create our own authorized_handler as original one was deprecated.

- CHANGES.rst
- invenio_oauthclient/version.py
> release: v1.1.3

- CHANGES.rst
- invenio_oauthclient/version.py
> release: v1.4.0a1

- invenio_oauthclient/contrib/cern_openid.py
- invenio_oauthclient/ext.py
- tests/test_contrib_cern_openid_rest.py
> contrib: handle login via token

- invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/_macros.html
- invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/signup.html
> forms: Fixes errors display in sign up form

- CHANGES.rst
- examples/app.py
- examples/cern_app.py
- examples/cern_app_rest.py
- examples/github_app.py
- examples/github_app_rest.py
- examples/globus_app.py
- examples/globus_app_rest.py
- examples/orcid_app.py
- examples/orcid_app_rest.py
- invenio_oauthclient/contrib/cern_openid.py
- invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/settings/index.html
- invenio_oauthclient/version.py
- invenio_oauthclient/views/settings.py
- setup.py
- tests/conftest.py
> Fix theme icons

- invenio_oauthclient/translations/de/LC_MESSAGES/messages.po
* add german translations
related inveniosoftware/invenio-app-rdm/issues/1664
> i18n: adds german translations

- .github/workflows/i18n-pull.yml
- .github/workflows/i18n-push.yml
- .github/workflows/tests.yml
- run-i18n-tests.sh
- run-tests.sh
tests: adds extract_messages dry command
> ci: adds i18n workflow

- invenio_oauthclient/contrib/keycloak/handlers.py
- invenio_oauthclient/contrib/keycloak/helpers.py
- invenio_oauthclient/contrib/openaire_aai.py
- tests/helpers.py
- tests/test_contrib_keycloak.py
- closes https://github.com/inveniosoftware/invenio-oauthclient/issues/296
> contrib: migrate openaire sandbox to keycloak

- invenio_oauthclient/utils.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/67
> utils: fix auto-confirm

- invenio_oauthclient/views/client.py
Closes https://github.com/CERNDocumentServer/cds-rdm/issues/78
> views: fix missing "next" redirect for auto login

- CHANGES.rst
- invenio_oauthclient/__init__.py
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
> release: v3.2.0

- invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/settings/index.html
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2301
> settings: Improve layout for a11y

- CHANGES.rst
- invenio_oauthclient/__init__.py
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
> release: v3.3.0

- CHANGES.rst
- invenio_oauthclient/__init__.py
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
> release: v3.4.1

- CHANGES.rst
- invenio_oauthclient/__init__.py
- invenio_oauthclient/admin.py
- invenio_oauthclient/contrib/cern.py
- invenio_oauthclient/contrib/cern_openid.py
- invenio_oauthclient/contrib/github.py
- invenio_oauthclient/contrib/globus.py
- invenio_oauthclient/contrib/keycloak/helpers.py
- invenio_oauthclient/contrib/openaire_aai.py
- invenio_oauthclient/contrib/orcid.py
- invenio_oauthclient/handlers/__init__.py
- invenio_oauthclient/handlers/rest.py
- invenio_oauthclient/handlers/token.py
- invenio_oauthclient/handlers/ui.py
- invenio_oauthclient/handlers/utils.py
- invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/login_user.html
- tests/test_contrib_keycloak.py
> Please describe briefly your pull request.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the …
> I18n-translations-backport

- CHANGES.rst
- invenio_oauthclient/__init__.py
- setup.cfg
- fix: setuptools require underscores instead of dashes
- release: v4.2.0
> rel v4 2 0
